# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [2, 4, 3]
show_hidden = true


[opener]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]
open = [{ run = 'nvim "$1"', block = true, for = "unix", mime = "text/*" }]
